
import { useResponsiveLayout } from "@context/LayoutContext";
import { StyleSheet } from "react-native";
import { useMemo } from "react";

export const useStylesDayCarousel = () => {
  const { isPhone, isWeb, width } = useResponsiveLayout();

  const styles = useMemo(() => StyleSheet.create({
    container: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      width: '100%',
      marginTop: 24,
      marginBottom: 8,
      gap: 8,
    },
    arrowContainer: {
      justifyContent: 'center',
      alignItems: 'center',
      height: '100%',
    },
    cardsRow: {
      flexDirection: 'row',
      gap: 24,
      justifyContent: 'center',
      alignItems: 'stretch',
      flex: 1,
    },
    card: {
      backgroundColor: '#fff',
      borderRadius: 18,
      padding: 24,
      minWidth: 240,
      maxWidth: 320,
      flex: 1,
      alignItems: 'center',
      shadowColor: '#00a69d',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.10,
      shadowRadius: 12,
      elevation: 6,
      borderWidth: 1,
      borderColor: 'rgba(0, 166, 157, 0.08)',
      marginHorizontal: 2,
    },
    cardHover: {
      shadowOpacity: 0.18,
      elevation: 10,
      borderColor: '#00a69d',
    },
    dayTitle: {
      fontSize: 24,
      fontWeight: '700',
      color: '#222',
      marginBottom: 18,
      textAlign: 'center',
      letterSpacing: 0.2,
    },
    miniCard: {
      backgroundColor: '#f7f7f7',
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginBottom: 10,
      width: 200,
      alignSelf: 'center',
      borderLeftWidth: 4,
      borderLeftColor: '#00a69d',
      alignItems: 'flex-start',
      shadowColor: '#00a69d',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    medicationText: {
      fontSize: 16,
      fontWeight: '600',
      color: '#222',
      marginBottom: 2,
    },
    medicationTime: {
      fontSize: 15,
      color: '#00a69d',
      fontWeight: '700',
      marginBottom: 2,
    },
    medicationDoses: {
      fontSize: 13,
      color: '#888',
      marginBottom: 0,
    },
    moreMedicationsText: {
      fontSize: 13,
      color: '#00a69d',
      marginTop: 4,
      fontWeight: '600',
      textAlign: 'center',
    },
    emptyMedication: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 60,
    },
    noMedicationsText: {
      color: '#888',
      fontSize: 16,
      textAlign: 'center',
      fontWeight: '400',
    },
    arrowButton: {
      backgroundColor: 'transparent',
      borderRadius: 50,
      padding: 8,
      marginHorizontal: 2,
      elevation: 0,
      shadowOpacity: 0,
    },
    modalMedicationCard: {
      backgroundColor: "#fff",
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      borderLeftWidth: 4,
      borderLeftColor: "#00a69d",
    },
    modalMedicationName: {
      fontSize: isWeb ? 20 : 18,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 12,
      textAlign: "center",
    },
    modalDetailRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
      paddingVertical: 4,
    },
    modalDetailLabel: {
      fontSize: isWeb ? 16 : 14,
      fontWeight: "600",
      color: "#555",
      marginLeft: 8,
      marginRight: 8,
      minWidth: 80,
    },
    modalDetailValue: {
      fontSize: isWeb ? 16 : 14,
      color: "#333",
      flex: 1,
      flexWrap: "wrap",
    },
    modalSeparator: {
      height: 1,
      backgroundColor: "#e0e0e0",
      marginVertical: 16,
    },
    modalEmptyText: {
      fontSize: isWeb ? 18 : 16,
      color: "#999",
      textAlign: "center",
      marginTop: 16,
      fontStyle: "italic",
    },
    urgencyHigh: {
      fontSize: isWeb ? 16 : 14,
      color: "#e74c3c",
      flex: 1,
      flexWrap: "wrap" as any,
      fontWeight: "bold",
    },
    urgencyMedium: {
      fontSize: isWeb ? 16 : 14,
      color: "#f39c12",
      flex: 1,
      flexWrap: "wrap" as any,
      fontWeight: "bold",
    },
    urgencyLow: {
      fontSize: isWeb ? 16 : 14,
      color: "#27ae60",
      flex: 1,
      flexWrap: "wrap" as any,
      fontWeight: "bold",
    },
  }), [isPhone, isWeb]);

  const customStyles = useMemo(() => StyleSheet.create({
    modal: {
      backgroundColor: "#fff",
      borderRadius: 24,
      paddingVertical: 36,
      paddingHorizontal: 32,
      alignItems: "center",
      elevation: 50,
      zIndex: 1000,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.25,
      shadowRadius: 24,
      borderWidth: 2,
      borderColor: "#00a69d",
    },
    overlay: {
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    title: {
      color: "#00a69d",
      fontWeight: "bold",
      fontSize: 24,
      marginBottom: 18,
      letterSpacing: 0.5,
      textShadowColor: "#b2f7ef",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    body: {
      alignItems: "center",
      marginBottom: 18,
    },
    buttons: {
      justifyContent: "center",
      width: "100%",
      marginTop: 12,
    },
    messageText: {},
  }), []);

  return { styles, customStyles, width, isPhone, isWeb };
};
