import { useResponsiveLayout } from "@context/LayoutContext";
import { StyleSheet } from "react-native";
import { useMemo } from "react";

export const stylesDayCarousel = () => {
  const { isPhone, isWeb, width } = useResponsiveLayout();

  const styles = useMemo(() => StyleSheet.create({
    container: {
      flex: 1,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      marginVertical: 0,
    },
    cardsRow: {
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
    },
    card: {
      width: 300,
      height: 300,
      marginHorizontal: 8,
      padding: 14,
      backgroundColor: "#fff",
      borderRadius: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      alignItems: "center",
      justifyContent: isPhone ? "center" : "flex-start",
    },
    cardHover: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 12,
      elevation: 8,
      transform: [{ scale: 1.04 }],
      zIndex: 2,
    },
    dayTitle: {
      fontSize: isWeb ? 24 : 20,
      fontWeight: "600",
      marginBottom: 12,
      color: "#333",
      textAlign: "center",
    },
    medicationText: {
      fontSize: isWeb ? 18 : 16,
      color: "#555",
      textAlign: "center",
      fontWeight: "600",
    },
    medicationItem: {
      alignItems: "center",
      marginVertical: 3,
      paddingVertical: 8,
      paddingHorizontal: 10,
      backgroundColor: "#f8f9fa",
      borderRadius: 8,
      minWidth: "90%",
      borderLeftWidth: 3,
      borderLeftColor: "#00a69d",
    },
    medicationTime: {
      fontSize: isWeb ? 14 : 12,
      color: "#00a69d",
      textAlign: "center",
      fontWeight: "500",
      marginTop: 2,
    },
    medicationDoses: {
      fontSize: isWeb ? 12 : 10,
      color: "#666",
      textAlign: "center",
      fontWeight: "400",
      marginTop: 1,
    },
    emptyMedication: {
      height: 24,
      justifyContent: "center",
      alignItems: "center",
    },
    arrowButton: {
      padding: 12,
      backgroundColor: "transparent",
      borderWidth: 0,
      shadowOpacity: 0,
      elevation: 0,
    },
    moreMedicationsText: {
      color: "#00a69d",
      marginTop: 5,
      textAlign: "center",
    },
    modalMedicationCard: {
      backgroundColor: "#fff",
      borderRadius: 12,
      padding: 16,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      borderLeftWidth: 4,
      borderLeftColor: "#00a69d",
    },
    modalMedicationName: {
      fontSize: isWeb ? 20 : 18,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 12,
      textAlign: "center",
    },
    modalDetailRow: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 8,
      paddingVertical: 4,
    },
    modalDetailLabel: {
      fontSize: isWeb ? 16 : 14,
      fontWeight: "600",
      color: "#555",
      marginLeft: 8,
      marginRight: 8,
      minWidth: 80,
    },
    modalDetailValue: {
      fontSize: isWeb ? 16 : 14,
      color: "#333",
      flex: 1,
      flexWrap: "wrap",
    },
    modalSeparator: {
      height: 1,
      backgroundColor: "#e0e0e0",
      marginVertical: 16,
    },
    modalEmptyText: {
      fontSize: isWeb ? 18 : 16,
      color: "#999",
      textAlign: "center",
      marginTop: 16,
      fontStyle: "italic",
    },
    urgencyHigh: {
      fontSize: isWeb ? 16 : 14,
      color: "#e74c3c",
      flex: 1,
      flexWrap: "wrap" as any,
      fontWeight: "bold",
    },
    urgencyMedium: {
      fontSize: isWeb ? 16 : 14,
      color: "#f39c12",
      flex: 1,
      flexWrap: "wrap" as any,
      fontWeight: "bold",
    },
    urgencyLow: {
      fontSize: isWeb ? 16 : 14,
      color: "#27ae60",
      flex: 1,
      flexWrap: "wrap" as any,
      fontWeight: "bold",
    },
  }), [isPhone, isWeb]);

  const customStyles = useMemo(() => StyleSheet.create({
    modal: {
      backgroundColor: "#fff",
      borderRadius: 24,
      paddingVertical: 36,
      paddingHorizontal: 32,
      alignItems: "center",
      elevation: 50,
      zIndex: 1000,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.25,
      shadowRadius: 24,
      borderWidth: 2,
      borderColor: "#00a69d",
    },
    overlay: {
      backgroundColor: "rgba(0, 0, 0, 0.5)",
    },
    title: {
      color: "#00a69d",
      fontWeight: "bold",
      fontSize: 24,
      marginBottom: 18,
      letterSpacing: 0.5,
      textShadowColor: "#b2f7ef",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    body: {
      alignItems: "center",
      marginBottom: 18,
    },
    buttons: {
      justifyContent: "center",
      width: "100%",
      marginTop: 12,
    },
    messageText: {},
  }), []);

  return { styles, customStyles, width, isPhone, isWeb };
};
