import { typeLanguages } from "./typesTranslations";

const en: typeLanguages = {
  addMedication: "Add medication",
  configurePillDispenser: "Configure pill dispenser",
  addPatient: "Add Patient",
  addPatientForm: "Here would be the form to add a patient",
  capsysDescription:
    "The smart pillbox is a connected device designed to facilitate daily medication management. It syncs with our mobile app to send automatic reminders, personalized alerts, and real-time notifications. Thanks to its functional design and integrated technology, it allows caregivers and users to maintain precise and error-free control over schedules, doses, and administration, improving treatment adherence and peace of mind",
  close: "Close",
  dearUser: "dear user",
  email: "Email",
  error: "Error",
  errorSignUp: "Error signing up, please try again later.",
  friday: "Friday",
  greeting: "Hello, {0}",
  headerTitle: "Header",
  languages: "Languages",
  logOut: "Log Out",
  login: "Login",
  menuHome: "Home",
  menuLogout: "Logout",
  menuProfile: "Profile",
  monday: "Monday",
  more: "more",
  noMedications: "No medications",
  notLoggedIn: "You are not logged in.",
  password: "Password",
  patientDescription: "Patient Description",
  patientName: "Patient Name",
  rememberMe: "Remember me",
  saturday: "Saturday",
  signUp: "Sign Up",
  success: "Success",
  successSignUp: "Sign up successful.",
  successSignUpMessage: "You can now log in with your credentials.",
  sunday: "Sunday",
  thursday: "Thursday",
  tuesday: "Tuesday",
  verifyEmail:
    "We have sent a verification email to your address. Please check your inbox and verify your email to complete the registration process.",
  wednesday: "Wednesday",
  welcomeUser: "Welcome, {{name}}!",
  welcome: "Welcome to MediTime",
  emailPlaceholder: "E.g. user@email.com",
  passwordPlaceholder: "Enter your password",
  loginButton: "Log In",
  forgotPassword: "Forgot your password?",
  createAccount: "Create new account",
  errorEmpty: "Please fill in all fields",
  errorEmail: "Enter a valid email",
  errorPassword:
    "Password must be at least 8 characters long and contain both letters and numbers",
  hasAccount: "Already have an account? Log in",
  errorNoSession: "No session data received",
  errorNoSessionMessage:
    "Please try logging in again or contact support if the issue persists.",
  successLogout: "Logged out successfully",
  successLogoutMessage: "You have successfully logged out. See you later!",
  age: "Age",
  years: "years",
  patientText: "Patient",
  medicationText: "Medication",
  dosage: "Dosage",
  dosagePlaceholder: "E.g. 1 pill, 500mg",
  noNameGiven: "No name given",
  conditions: "Conditions",
  allergies: "Allergies",
  name: "Name",
  medicationsManagement: "Medications Management",
  manageMedicationsDescription: "Manage your patients' medication schedules",
  type: "Type",
  daysText: "Days",
  selectTime: "Select Time",
  addSchedule: "Add Schedule",
  schedulesScheduled: "Schedules scheduled",
  schedulesNotScheduled: "Schedules not scheduled",
  addMedicationsOnTop: "Add medications using the top form",
  hour: "Hour",
  hours: "Hours",
  days: {
    monday: "Mo",
    tuesday: "Tu",
    wednesday: "We",
    thursday: "Th",
    friday: "Fr",
    saturday: "Sa",
    sunday: "Su",
  },
  dosageTypes: JSON.stringify(["pills", "mg", "units"]),
  urgency: JSON.stringify({ low: "Low", medium: "Medium", high: "High" }),
  unknown: "Unknown",
  medicationPlaceholder: "E.g. Paracetamol, Ibuprofen",
  clearMedication: "Clear Medication",
  deleteMedication: "Delete Medication",
  intervalHours: "Interval Hours",
  intervalHoursPlaceholder: "E.g. 8 (every 8 hours)",
  stock: "Stock",
  stockPlaceholder: "E.g. 30 (pills available)",
  requiredDoses: "Required Doses",
  requiredDosesPlaceholder: "E.g. 21 (total needed)",
  requiredDosesDescription: "Total number of doses to complete the treatment",
  urgencyText: "Urgency",
  settings: "Settings",
  save: "Save",
  enableNotifications: "Enable notifications",
  searchMedications: "Search medications",
  medicationNotFound: "Medication not found",
  noMedicationsFoundMessage: "No medications found matching your search",
  loadingMedications: "Loading medications...",
  medicationRequired: "Medication required",
  dosageRequired: "Dosage required (greater than 0)",
  daysRequired: "Select at least one day",
  intervalRequired: "Interval hours required",
  urgencyRequired: "Urgency level required",
  formValidationTitle: "Required Fields",
  formValidationMessage: "Please complete the following fields:",
  searchHint: "Type at least 3 characters",
  uploadImage: "Upload image",
  description: "Description",
  caregiver: "Caregiver",
  patient: "Patient",
  both: "Both",
  fullName: "Full Name",
  numberPhone: "Phone Number",
  userImage: "User Image",
  noImage: "No Image",
  role: "Role",
  namePatient: "Name: {{interpolateMessage}}",
  // PDF Report translations
  pdfReportTitle: "Medical Report",
  generateReport: "Generate PDF Report",
  pdfGeneratedTitle: "PDF Generated",
  pdfGeneratedMessage: "The medical report has been downloaded successfully.",
  pdfSavedMessage: "The report was saved successfully.",
  pdfErrorMessage: "There was an error generating the report. Please try again.",
  noMedicationsTitle: "No Medications",
  noMedicationsReportMessage: "There are no medications to include in the report.",
  errorTitle: "Error",
  generating: "Generating...",

  // PDF Content translations
  pdfMedicalReportTitle: "Medication Management Report",
  pdfGeneratedOn: "Generated on",
  pdfPatientInformation: "📋 Patient Information",
  pdfPatientLabel: "Patient",
  pdfTotalMedicationsLabel: "Total Medications",
  pdfActiveTreatmentsLabel: "Active Treatments",
  pdfLastUpdateLabel: "Last Update",
  pdfGeneralStatistics: "📊 General Statistics",
  pdfAverageAdherence: "Average Adherence",
  pdfActiveMedications: "Active Medications",
  pdfDailyAverage: "Daily Average",
  pdfPreferredTime: "Preferred Time",
  pdfMedicationDetails: "💊 Medication Details",
  pdfNoMedicationsRegistered: "No medications registered.",
  pdfDosageLabel: "Dosage",
  pdfScheduleLabel: "Schedule",
  pdfDaysLabel: "Days",
  pdfAdherenceLabel: "Adherence",
  pdfNotSpecified: "Not specified",
  pdfNotSpecifiedDays: "Not specified",
  pdfMedicationDefault: "Medication",
  pdfFooterText1: "This report was automatically generated by the MediTime application.",
  pdfFooterText2: "For medical consultations, always consult with your healthcare professional.",

  // Time periods for PDF
  morning: "Morning",
  afternoon: "Afternoon",
  night: "Night",
};

export default en;
