import { typeLanguages } from "./typesTranslations";

const en: typeLanguages = {
  addMedication: "Add medication",
  addPatient: "Add Patient",
  addPatientForm: "Here would be the form to add a patient",
  capsysDescription:
    "The smart pillbox is a connected device designed to facilitate daily medication management. It syncs with our mobile app to send automatic reminders, personalized alerts, and real-time notifications. Thanks to its functional design and integrated technology, it allows caregivers and users to maintain precise and error-free control over schedules, doses, and administration, improving treatment adherence and peace of mind",
  close: "Close",
  dearUser: "dear user",
  email: "Email",
  error: "Error",
  errorSignUp: "Error signing up, please try again later.",
  friday: "Friday",
  greeting: "Hello, {0}",
  headerTitle: "Header",
  languages: "Languages",
  logOut: "Log Out",
  login: "Login",
  menuHome: "Home",
  menuLogout: "Logout",
  menuProfile: "Profile",
  monday: "Monday",
  more: "more",
  noMedications: "No medications",
  notLoggedIn: "You are not logged in.",
  password: "Password",
  patientDescription: "Patient Description",
  patientName: "Patient Name",
  rememberMe: "Remember me",
  saturday: "Saturday",
  signUp: "Sign Up",
  success: "Success",
  successSignUp: "Sign up successful.",
  successSignUpMessage: "You can now log in with your credentials.",
  sunday: "Sunday",
  thursday: "Thursday",
  tuesday: "Tuesday",
  verifyEmail:
    "We have sent a verification email to your address. Please check your inbox and verify your email to complete the registration process.",
  wednesday: "Wednesday",
  welcomeUser: "Welcome, {{name}}!",
  welcome: "Welcome to MediTime",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Password",
  loginButton: "Log In",
  forgotPassword: "Forgot your password?",
  createAccount: "Create new account",
  errorEmpty: "Please fill in all fields",
  errorEmail: "Enter a valid email",
  errorPassword:
    "Password must be at least 8 characters long and contain both letters and numbers",
  hasAccount: "Already have an account? Log in",
  errorNoSession: "No session data received",
  errorNoSessionMessage:
    "Please try logging in again or contact support if the issue persists.",
  successLogout: "Logged out successfully",
  successLogoutMessage: "You have successfully logged out. See you later!",
  age: "Age",
  years: "years",
  patientText: "Patient",
  medicationText: "Medication",
  dosage: "Dosage",
  dosagePlaceholder: "Dosage (e.g., {0})",
  noNameGiven: "No name given",
  conditions: "Conditions",
  allergies: "Allergies",
  name: "Name",
  medicationsManagement: "Medications Management",
  type: "Type",
  daysText: "Days",
  selectTime: "Select Time",
  addSchedule: "Add Schedule",
  schedulesScheduled: "Schedules scheduled",
  schedulesNotScheduled: "Schedules not scheduled",
  addMedicationsOnTop: "Add medications using the top form",
  hour: "Hour",
  days: {
    monday: "Mo",
    tuesday: "Tu",
    wednesday: "We",
    thursday: "Th",
    friday: "Fr",
    saturday: "Sa",
    sunday: "Su",
  },
  dosageTypes: JSON.stringify(["pills", "mg", "units"]),
  urgency: JSON.stringify({ low: "Low", medium: "Medium", high: "High" }),
  unknown: "Unknown",
  medicationPlaceholder: "E.g. Loratadine",
  clearMedication: "Clear Medication",
  deleteMedication: "Delete Medication",
  intervalHours: "Interval Hours",
  intervalHoursPlaceholder: "E.g. 8",
  stock: "Stock",
  stockPlaceholder: "E.g. 30",
  urgencyText: "Urgency",
  namePatient: "Name: {{interpolateMessage}}",
  // User Settings Component
  settings: "Settings",
  save: "Save",
  enableNotifications: "Enable notifications",
  uploadImage: "Upload image",
  description: "Description",
  footerDescription: "Intelligent medication management system for healthcare",
  caregiver: "Caregiver",
  patient: "Patient",
  both: "Both",
  fullName: "Full Name",
  numberPhone: "Phone Number",
  userImage: "User Image",
  noImage: "No Image",
  role: "Role",
  nameRequired: "Name is required",
  phoneRequired: "Phone number is required",
  phoneFormatError: "Phone number must be at least 10 digits",
  dataUpdated: "Data updated successfully",
  errorUserImage: "Error uploading user image",
  errorIdUser: "Error getting user ID",
  imageUploadSuccess: "Image uploaded successfully",
  dashboard: "Dashboard",
  home: "Home",
  pillboxSettings: "Pillbox Settings",
  pillboxDescription:
    "In this section, you can set up your pill organizer by following the instructions provided by Capsy. Make sure to place each medication in the correct compartment and verify that it is properly positioned.",
  // Patient management translations
  searchExisting: "Search existing",
  createNew: "Create new",
  searchPlaceholder: "Search by name or email",
  search: "Search",
  changePhoto: "Change photo",
  addPhoto: "Add photo",
  searchByEmailOrPhone: "Search by email or phone",
  userNotFound: "User not found",
  required: "Required",
  optional: "Optional",
  deletePatient: "Delete Patient",
  confirmDeletePatient: "Are you sure you want to delete this patient?",
  delete: "Delete",
  cancel: "Cancel",
  patientCreatedSuccessfully: "Patient created successfully",
  patientDeletedSuccessfully: "Patient deleted successfully",
  errorCreatingPatient: "Error creating patient",
  errorDeletingPatient: "Error deleting patient",
  fieldRequired: "This field is required",
  separateWithCommas: "Separate with commas",
  creating: "Creating...",
  createPatient: "Create Patient",
  adding: "Adding...",
  phone: "Phone",
  // Edit patient translations
  editPatient: "Edit Patient",
  editPatientInfo: "Edit Patient Information",
  updating: "Updating...",
  updatePatient: "Update Patient",
  patientUpdatedSuccessfully: "Patient updated successfully",
  errorUpdatingPatient: "Error updating patient",
  // Unassign patient translations
  unassignPatient: "Unassign Patient",
  confirmUnassignPatient:
    "Are you sure you want to unassign {0} from your care? The patient will not be deleted, they will just no longer be under your care.",
  unassign: "Unassign",
  patientUnassignedSuccessfully: "{0} has been unassigned successfully.",
  errorUnassigningPatient: "Error unassigning patient",
  networkError: "Network error",
  serverError: "Server connection error",
  // Caregiver validation translations
  caregiverCannotBePatient: "Caregivers cannot be assigned as patients",
  roleCaregiver: "Caregiver",
  rolePatient: "Patient",
  patientAlreadyAssigned: "Patient is already assigned to this caregiver",
  roleLabel: "Role",
  // Validation error messages
  invalidName: "Name can only contain letters and spaces",
  invalidPhone: "Phone must be exactly 10 digits",
  invalidEmail: "Please enter a valid email address",
  invalidAge: "Age must be a number between 1 and 99",
  phoneAlreadyExists: "This phone number is already registered by another user",
  emailAlreadyExists:
    "This email address is already registered by another user",
  // Additional error messages
  userDataNotAvailable: "User data not available",
  permissionDenied: "Permission denied",
  imageUploadedSuccessfully: "Image uploaded successfully",
  failedToUploadImage: "Failed to upload image",
  errorUploadingImage: "Error uploading image",
  networkErrorOccurred: "Network error occurred",
  // Patient Create Form additional translations
  permissionCameraRequired: "Permission to access camera roll is required!",
  imageSelectedWillUpload:
    "Image selected. It will be uploaded when creating the patient.",
  errorSelectingImage: "Error selecting image",
  errorUploadingImagePatientCreated:
    "Error uploading image. Patient will be created without image.",
  failedToCreatePatient: "Failed to create patient",
  changeImage: "Change image",
  selectImage: "Select image",
  removeImage: "Remove",
  initialBotMessage:
    "Hello! I'm your virtual assistant. How can I help you today?",
  history: "History",
  newConversation: "New conversation",
  clearHistory: "Clear history",
  askYourQuestion: "Ask your question here...",
  selectConversation: "Select a conversation",
  typing: "Typing...",
  send: "Send",
  chatbotTitle: "Health Virtual Assistant",
  loginRequired: "Login required",
  loginRequiredMessage: "Please log in to access this feature.",
  chatbot: "MediBot",
  selectPatient: "Select Patient",
  selectPatientSubtitle: "Which patient is this pillbox for?",
  noPatientsAvailable: "No patients available.",
  addPatientsFirst: "Add patients first.",
  pillboxConfiguration: "Pillbox Configuration",
  compartment: "Compartment",
  medication: "Medication",
  dose: "Dose",
  dosePlaceholder: "e.g: 500mg",
  sendToPillbox: "Send to Pillbox",
  connecting: "Connecting...",
  confirmSend: "Confirm Send",
  pillboxWillBeConfigured: "The pillbox will be configured with:",
  continueQuestion: "Continue?",
  pleaseSelectPatient: "Please select a patient",
  pleaseAddMedication: "Please add at least one medication",
  configurationSentSuccessfully: "Configuration sent to pillbox successfully",
  connectionTimeout:
    "Connection timeout. Verify that the pillbox is turned on and connected.",
  verifyPillboxConnection:
    "Could not connect to pillbox. Verify:\n\n1. The pillbox is turned on\n2. You're connected to the same WiFi network\n3. The IP address 192.168.4.1 is correct",
  couldNotConnectToPillbox: "Could not load patients",
  verifyWifiConnection: "Could not load patient medications",
  couldNotEstablishConnection: "Could not establish connection with pillbox",
  pillboxError: "Pillbox error",
  pill: "pill",
  pills: "pills",
  scheduleAndTiming: "Schedule & Timing",
  startTime: "Start time",
  addTimeSlot: "Add time slot",
  removeTime: "Remove",
  timingConfiguration: "Timing configuration",
  timeFormat: "Format: HH:MM (24 hours)",
  invalidTimeFormat: "Invalid time format",
  timeSlotAdded: "Time slot added",
  timeSlotRemoved: "Time slot removed",
  schedulingOptional: "Schedule configuration is optional",
  schedulingRequired:
    "Schedule configuration is required - please add at least one time slot",
  pillboxManagement: "Pillbox Management",
  assignedPillbox: "Assigned pillbox",
  pillboxAssignedTo: "Pillbox assigned to",
  pillboxId: "Pillbox ID",
  configuredOn: "Configured",
  removePillbox: "Remove Pillbox",
  assignPillboxTo: "Assign pillbox to",
  pillboxIdLabel: "Pillbox ID",
  pillboxIdPlaceholder: "Ex: PILL-001",
  pillboxIdHelp: "Enter the unique identifier of your pillbox device",
  confirmRemoval: "Confirm removal",
  confirmRemovalMessage:
    "Are you sure you want to remove the pillbox from {name}? All saved configuration will be lost.",
  pillboxIdRequired: "Please enter the pillbox ID",
  allConfigurationWillBeLost: "All saved configuration will be lost",
  remove: "Remove",
  configurationSavedInCapsy: "Configuration saved in Capsy successfully",
  intervalMustBeGreaterThanZero: "Interval must be greater than 0 hours",
} as const;

export default en;
