import { typeLanguages } from "./typesTranslations";

const en: typeLanguages = {
  addMedication: "Add medication",
  configurePillDispenser: "Configure pill dispenser",
  addPatient: "Add Patient",
  addPatientForm: "Here would be the form to add a patient",
  capsysDescription:
    "The smart pillbox is a connected device designed to facilitate daily medication management. It syncs with our mobile app to send automatic reminders, personalized alerts, and real-time notifications. Thanks to its functional design and integrated technology, it allows caregivers and users to maintain precise and error-free control over schedules, doses, and administration, improving treatment adherence and peace of mind",
  close: "Close",
  dearUser: "dear user",
  email: "Email",
  error: "Error",
  errorSignUp: "Error signing up, please try again later.",
  friday: "Friday",
  greeting: "Hello, {0}",
  headerTitle: "Header",
  languages: "Languages",
  logOut: "Log Out",
  login: "Login",
  menuHome: "Home",
  menuLogout: "Logout",
  menuProfile: "Profile",
  monday: "Monday",
  more: "more",
  noMedications: "No medications",
  notLoggedIn: "You are not logged in.",
  password: "Password",
  patientDescription: "Patient Description",
  patientName: "Patient Name",
  rememberMe: "Remember me",
  saturday: "Saturday",
  signUp: "Sign Up",
  success: "Success",
  successSignUp: "Sign up successful.",
  successSignUpMessage: "You can now log in with your credentials.",
  sunday: "Sunday",
  thursday: "Thursday",
  tuesday: "Tuesday",
  verifyEmail:
    "We have sent a verification email to your address. Please check your inbox and verify your email to complete the registration process.",
  wednesday: "Wednesday",
  welcomeUser: "Welcome, {{name}}!",
  welcome: "Welcome to MediTime",
  emailPlaceholder: "Email",
  passwordPlaceholder: "Password",
  loginButton: "Log In",
  forgotPassword: "Forgot your password?",
  createAccount: "Create new account",
  errorEmpty: "Please fill in all fields",
  errorEmail: "Enter a valid email",
  errorPassword:
    "Password must be at least 8 characters long and contain both letters and numbers",
  hasAccount: "Already have an account? Log in",
  errorNoSession: "No session data received",
  errorNoSessionMessage:
    "Please try logging in again or contact support if the issue persists.",
  successLogout: "Logged out successfully",
  successLogoutMessage: "You have successfully logged out. See you later!",
  age: "Age",
  years: "years",
  patientText: "Patient",
  medicationText: "Medication",
  dosage: "Dosage",
  dosagePlaceholder: "Dosage (e.g., {0})",
  noNameGiven: "No name given",
  conditions: "Conditions",
  allergies: "Allergies",
  name: "Name",
  medicationsManagement: "Medications Management",
  manageMedicationsDescription: "Manage your patients' medication schedules",
  type: "Type",
  daysText: "Days",
  selectTime: "Select Time",
  addSchedule: "Add Schedule",
  schedulesScheduled: "Schedules scheduled",
  schedulesNotScheduled: "Schedules not scheduled",
  addMedicationsOnTop: "Add medications using the top form",
  hour: "Hour",
  hours: "Hours",
  days: {
    monday: "Mo",
    tuesday: "Tu",
    wednesday: "We",
    thursday: "Th",
    friday: "Fr",
    saturday: "Sa",
    sunday: "Su",
  },
  dosageTypes: JSON.stringify(["pills", "mg", "units"]),
  urgency: JSON.stringify({ low: "Low", medium: "Medium", high: "High" }),
  unknown: "Unknown",
  medicationPlaceholder: "E.g. Loratadine",
  clearMedication: "Clear Medication",
  deleteMedication: "Delete Medication",
  intervalHours: "Interval Hours",
  intervalHoursPlaceholder: "E.g. 8",
  stock: "Stock",
  stockPlaceholder: "E.g. 30",
  requiredDoses: "Required Doses",
  requiredDosesPlaceholder: "E.g. 30",
  requiredDosesDescription: "Total number of doses to complete the treatment",
  urgencyText: "Urgency",
  namePatient: "Name: {{interpolateMessage}}",
  // User Settings Component
  settings: "Settings",
  save: "Save",
  enableNotifications: "Enable notifications",
  searchMedications: "Search medications",
  medicationNotFound: "Medication not found",
  noMedicationsFoundMessage: "No medications found matching your search",
  loadingMedications: "Loading medications...",
  medicationRequired: "Medication required",
  dosageRequired: "Dosage required (greater than 0)",
  daysRequired: "Select at least one day",
  intervalRequired: "Interval hours required",
  urgencyRequired: "Urgency level required",
  formValidationTitle: "Required Fields",
  formValidationMessage: "Please complete the following fields:",
  searchHint: "Type at least 3 characters",
  uploadImage: "Upload image",
  description: "Description",
  caregiver: "Caregiver",
  patient: "Patient",
  both: "Both",
  fullName: "Full Name",
  numberPhone: "Phone Number",
  userImage: "User Image",
  noImage: "No Image",
  role: "Role",
  nameRequired: "Name is required",
  phoneRequired: "Phone number is required",
  phoneFormatError: "Phone number must be at least 10 digits",
  dataUpdated: "Data updated successfully",
  errorUserImage: "Error uploading user image",
  errorIdUser: "Error getting user ID",
  imageUploadSuccess: "Image uploaded successfully",
  dashboard: "Dashboard",
  home: "Home",
  pillboxSettings: "Pillbox Settings",
  // Patient management translations
  searchExisting: "Search existing",
  createNew: "Create new",
  searchPlaceholder: "Search by name or email",
  search: "Search",
  changePhoto: "Change photo",
  addPhoto: "Add photo",
  searchByEmailOrPhone: "Search by email or phone",
  userNotFound: "User not found",
  required: "Required",
  optional: "Optional",
  deletePatient: "Delete Patient",
  confirmDeletePatient: "Are you sure you want to delete this patient?",
  delete: "Delete",
  cancel: "Cancel",
  patientCreatedSuccessfully: "Patient created successfully",
  patientDeletedSuccessfully: "Patient deleted successfully",
  errorCreatingPatient: "Error creating patient",
  errorDeletingPatient: "Error deleting patient",
  fieldRequired: "This field is required",
  separateWithCommas: "Separate with commas",
  creating: "Creating...",
  createPatient: "Create Patient",
  adding: "Adding...",
  phone: "Phone",
  // Edit patient translations
  editPatient: "Edit Patient",
  editPatientInfo: "Edit Patient Information",
  updating: "Updating...",
  updatePatient: "Update Patient",
  patientUpdatedSuccessfully: "Patient updated successfully",
  errorUpdatingPatient: "Error updating patient",
  // Unassign patient translations
  unassignPatient: "Unassign Patient",
  confirmUnassignPatient:
    "Are you sure you want to unassign {0} from your care? The patient will not be deleted, they will just no longer be under your care.",
  unassign: "Unassign",
  patientUnassignedSuccessfully: "{0} has been unassigned successfully.",
  errorUnassigningPatient: "Error unassigning patient",
  networkError: "Network error",
  medicationAddedSuccessfully: "Medication added successfully!",
  errorSavingMedication: "Error saving medication",
  serverError: "Server connection error",
  // Caregiver validation translations
  caregiverCannotBePatient: "Caregivers cannot be assigned as patients",
  roleCaregiver: "Caregiver",
  rolePatient: "Patient",
  patientAlreadyAssigned: "Patient is already assigned to this caregiver",
  roleLabel: "Role",
  // Validation error messages
  invalidName: "Name can only contain letters and spaces",
  invalidPhone: "Phone must be exactly 10 digits",
  invalidEmail: "Please enter a valid email address",
  invalidAge: "Age must be a number between 1 and 99",
  phoneAlreadyExists: "This phone number is already registered by another user",
  emailAlreadyExists:
    "This email address is already registered by another user",
  // Additional error messages
  userDataNotAvailable: "User data not available",
  permissionDenied: "Permission denied",
  imageUploadedSuccessfully: "Image uploaded successfully",
  failedToUploadImage: "Failed to upload image",
  errorUploadingImage: "Error uploading image",
  networkErrorOccurred: "Network error occurred",
  // Patient Create Form additional translations
  permissionCameraRequired: "Permission to access camera roll is required!",
  imageSelectedWillUpload:
    "Image selected. It will be uploaded when creating the patient.",
  errorSelectingImage: "Error selecting image",
  errorUploadingImagePatientCreated:
    "Error uploading image. Patient will be created without image.",
  failedToCreatePatient: "Failed to create patient",
  changeImage: "Change image",
  selectImage: "Select image",
  removeImage: "Remove",
  initialBotMessage:
    "Hello! I'm your virtual assistant. How can I help you today?",
  history: "History",
  newConversation: "New conversation",
  clearHistory: "Clear history",
  askYourQuestion: "Ask your question here...",
  selectConversation: "Select a conversation",
  typing: "Typing...",
  send: "Send",
  chatbotTitle: "Health Virtual Assistant",
  loginRequired: "Login required",
  loginRequiredMessage: "Please log in to access this feature.",
  chatbot: "MediBot",
  // PDF Report translations
  pdfReportTitle: "Medical Report",
  generateReport: "Generate PDF Report",
  pdfGeneratedTitle: "PDF Generated",
  pdfGeneratedMessage: "The medical report has been downloaded successfully.",
  pdfSavedMessage: "The report was saved successfully.",
  pdfErrorMessage: "There was an error generating the report. Please try again.",
  noMedicationsTitle: "No Medications",
  noMedicationsReportMessage: "There are no medications to include in the report.",
  errorTitle: "Error",
  generating: "Generating...",
  loadingPatient: "Loading patient ...",
  // PDF Content translations
  pdfMedicalReportTitle: "Medication Management Report",
  pdfGeneratedOn: "Generated on",
  pdfPatientInformation: "📋 Patient Information",
  pdfPatientLabel: "Patient",
  pdfTotalMedicationsLabel: "Total Medications",
  pdfActiveTreatmentsLabel: "Active Treatments",
  pdfLastUpdateLabel: "Last Update",
  pdfGeneralStatistics: "📊 General Statistics",
  pdfAverageAdherence: "Average Adherence",
  pdfActiveMedications: "Active Medications",
  pdfDailyAverage: "Daily Average",
  pdfPreferredTime: "Preferred Time",
  pdfMedicationDetails: "💊 Medication Details",
  pdfNoMedicationsRegistered: "No medications registered.",
  pdfDosageLabel: "Dosage",
  pdfScheduleLabel: "Schedule",
  pdfDaysLabel: "Days",
  pdfAdherenceLabel: "Adherence",
  pdfNotSpecified: "Not specified",
  pdfNotSpecifiedDays: "Not specified",
  pdfMedicationDefault: "Medication",
  pdfFooterText1: "This report was automatically generated by the MediTime application.",
  pdfFooterText2: "For medical consultations, always consult with your healthcare professional.",
  // Time periods for PDF
  morning: "Morning",
  afternoon: "Afternoon",
  night: "Night",
} as const;

export default en;
