import { typeLanguages } from "./typesTranslations";

const es: typeLanguages = {
  addMedication: "Agregar medicamento",
  addPatient: "Agregar Paciente",
  addPatientForm: "Aquí estaría el formulario para agregar un paciente",
  capsysDescription:
    "El pastillero inteligente es un dispositivo conectado diseñado para facilitar la gestión diaria de medicamentos. Se sincroniza con nuestra app móvil para enviar recordatorios automáticos, alertas personalizadas y notificaciones en tiempo real. Gracias a su diseño funcional y tecnología integrada, permite a cuidadores y usuarios llevar un control preciso y sin errores sobre horarios, dosis y administración, mejorando la adherencia al tratamiento y la tranquilidad en el cuidado",
  close: "Cerrar",
  dearUser: "querido usuario",
  email: "Correo electrónico",
  error: "Error",
  errorSignUp: "Error al registrarse, por favor intente más tarde.",
  friday: "Viernes",
  greeting: "Hola, {0}",
  headerTitle: "Encabezado",
  languages: "Lenguajes",
  logOut: "Cerrar sesión",
  login: "Iniciar sesión",
  menuHome: "Inicio",
  menuLogout: "Cerrar sesión",
  menuProfile: "Perfil",
  monday: "Lunes",
  more: "más",
  noMedications: "Sin medicamentos",
  notLoggedIn: "No has iniciado sesión.",
  password: "Contraseña",
  patientDescription: "Descripción del paciente",
  patientName: "Nombre del paciente",
  rememberMe: "Recuérdame",
  saturday: "Sábado",
  signUp: "Registrarse",
  success: "Éxito",
  successSignUp: "Registro exitoso.",
  successSignUpMessage: "Ahora puedes iniciar sesión con tus credenciales.",
  sunday: "Domingo",
  thursday: "Jueves",
  tuesday: "Martes",
  verifyEmail:
    "Hemos enviado un correo de verificación a tu dirección. Por favor, revisa tu bandeja de entrada y verifica tu correo para completar el proceso de registro.",
  wednesday: "Miércoles",
  welcome: "Bienvenido",
  welcomeUser: "Bienvenido, {{name}}!",
  emailPlaceholder: "Correo electrónico",
  passwordPlaceholder: "Contraseña",
  loginButton: "Iniciar Sesión",
  forgotPassword: "¿Olvidaste tu contraseña?",
  createAccount: "Crear nueva cuenta",
  errorEmpty: "Por favor complete todos los campos",
  errorEmail: "Ingrese un email válido",
  errorPassword:
    "La contraseña debe tener al menos 8 caracteres y contener letras y números",
  hasAccount: "¿Ya tienes una cuenta? Inicia sesión",
  errorNoSession: "No se recibieron datos de sesión",
  errorNoSessionMessage:
    "Por favor, intenta iniciar sesión nuevamente o contacta al soporte si el problema persiste.",
  successLogout: "Sesión cerrada exitosamente",
  successLogoutMessage: "Has cerrado sesión correctamente. ¡Hasta luego!",
  age: "Edad",
  years: "años",
  patientText: "Paciente",
  medicationText: "Medicamento",
  dosage: "Dosis",
  dosagePlaceholder: " Dosis (ej. {0})",
  noNameGiven: "No se proporcionó un nombre",
  conditions: "Condiciones",
  allergies: "Alergias",
  name: "Nombre",
  medicationsManagement: "Gestión de Medicamentos",
  type: "Tipo",
  daysText: "Días",
  selectTime: "Seleccionar Hora",
  addSchedule: "Agregar Horario",
  schedulesScheduled: "Horarios programados",
  schedulesNotScheduled: "Horarios no programados",
  addMedicationsOnTop: "Agrega medicamentos usando el formulario superior",
  hour: "Hora",
  days: {
    monday: "Lu",
    tuesday: "Ma",
    wednesday: "Mi",
    thursday: "Ju",
    friday: "Vi",
    saturday: "Sa",
    sunday: "Do",
  },
  dosageTypes: JSON.stringify(["pastillas", "mg", "unidades"]),
  urgency: JSON.stringify({ low: "Baja", medium: "Media", high: "Alta" }),
  unknown: "Desconocido",
  medicationPlaceholder: "P. ej. Loratadina",
  clearMedication: "Limpiar Medicamento",
  deleteMedication: "Eliminar Medicamento",
  intervalHours: "Horas de intervalo",
  intervalHoursPlaceholder: "Horas de intervalo (ej. 8)",
  stock: "Stock",
  stockPlaceholder: "Ej. 30",
  urgencyText: "Urgencia",
  namePatient: "Nombre: {{interpolateMessage}}",
  // User Settings Component
  settings: "Ajustes",
  save: "Guardar",
  enableNotifications: "Activar notificaciones",
  uploadImage: "Subir imagen",
  description: "Descripción",
  caregiver: "Cuidador",
  patient: "Paciente",
  both: "Ambos",
  fullName: "Nombre completo",
  numberPhone: "Número de teléfono",
  userImage: "Imagen de usuario",
  noImage: "Sin imagen",
  role: "Rol",
  nameRequired: "El nombre es obligatorio",
  phoneRequired: "El número de teléfono es obligatorio",
  phoneFormatError: "El número de teléfono debe tener 10 dígitos",
  dataUpdated: "Datos actualizados correctamente",
  errorUserImage: "Error al subir la imagen del usuario",
  errorIdUser: "Error al obtener el identificador del usuario",
  imageUploadSuccess: "Imagen subida correctamente",
  dashboard: "Panel de usuario",
  home: "Inicio",
  pillboxSettings: "Configuración del pastillero",
  // Patient management translations
  searchExisting: "Buscar existente",
  createNew: "Crear nuevo",
  searchPlaceholder: "Buscar por nombre o correo",
  search: "Buscar",
  changePhoto: "Cambiar foto",
  addPhoto: "Agregar foto",
  searchByEmailOrPhone: "Buscar por correo o teléfono",
  userNotFound: "Usuario no encontrado",
  required: "Obligatorio",
  optional: "Opcional",
  deletePatient: "Eliminar Paciente",
  confirmDeletePatient: "¿Estás seguro de que quieres eliminar este paciente?",
  delete: "Eliminar",
  cancel: "Cancelar",
  patientCreatedSuccessfully: "Paciente creado exitosamente",
  patientDeletedSuccessfully: "Paciente eliminado exitosamente",
  errorCreatingPatient: "Error al crear paciente",
  errorDeletingPatient: "Error al eliminar paciente",
  fieldRequired: "Este campo es obligatorio",
  separateWithCommas: "Separar con comas",
  creating: "Creando...",
  createPatient: "Crear Paciente",
  adding: "Agregando...",
  phone: "Teléfono",
  // Edit patient translations
  editPatient: "Editar Paciente",
  editPatientInfo: "Editar Información del Paciente",
  updating: "Actualizando...",
  updatePatient: "Actualizar Paciente",
  patientUpdatedSuccessfully: "Paciente actualizado exitosamente",
  errorUpdatingPatient: "Error al actualizar paciente",
  // Unassign patient translations
  unassignPatient: "Desasignar Paciente",
  confirmUnassignPatient:
    "¿Estás seguro de que quieres desasignar a {0} de tu cuidado? El paciente no será eliminado, solo dejará de estar bajo tu cuidado.",
  unassign: "Desasignar",
  patientUnassignedSuccessfully: "{0} ha sido desasignado exitosamente.",
  errorUnassigningPatient: "Error al desasignar paciente",
  networkError: "Error de red",
  serverError: "Error de conexión al servidor",
  // Caregiver validation translations
  caregiverCannotBePatient:
    "Los cuidadores no pueden ser asignados como pacientes",
  roleCaregiver: "Cuidador",
  rolePatient: "Paciente",
  patientAlreadyAssigned: "El paciente ya está asignado a este cuidador",
  roleLabel: "Rol",
  // Validation error messages
  invalidName: "El nombre solo puede contener letras y espacios",
  invalidPhone: "El teléfono debe tener exactamente 10 dígitos",
  invalidEmail: "Por favor ingrese una dirección de correo válida",
  invalidAge: "La edad debe ser un número entre 1 y 99",
  phoneAlreadyExists:
    "Este número de teléfono ya está registrado por otro usuario",
  emailAlreadyExists:
    "Este correo electrónico ya está registrado por otro usuario",
  // Additional error messages
  userDataNotAvailable: "Datos de usuario no disponibles",
  permissionDenied: "Permiso denegado",
  imageUploadedSuccessfully: "Imagen subida exitosamente",
  failedToUploadImage: "Error al subir la imagen",
  errorUploadingImage: "Error al subir la imagen",
  networkErrorOccurred: "Error de red",
  // Patient Create Form additional translations
  permissionCameraRequired:
    "¡Se requiere permiso para acceder a la galería de fotos!",
  imageSelectedWillUpload:
    "Imagen seleccionada. Se subirá al crear el paciente.",
  errorSelectingImage: "Error al seleccionar imagen",
  errorUploadingImagePatientCreated:
    "Error al subir imagen. El paciente se creará sin imagen.",
  failedToCreatePatient: "Error al crear paciente",
  changeImage: "Cambiar imagen",
  selectImage: "Seleccionar imagen",
  removeImage: "Quitar",
  initialBotMessage:
    "¡Hola! Soy tu asistente virtual. ¿En qué puedo ayudarte hoy?",
  history: "Historial",
  newConversation: "Nueva conversación",
  clearHistory: "Borrar historial",
  askYourQuestion: "Haz tu pregunta aquí...",
  selectConversation: "Selecciona una conversación",
  typing: "Escribiendo...",
  send: "Enviar",
  chatbotTitle: "Asistente Virtual de Salud",
  loginRequired: "Inicio de sesión requerido",
  loginRequiredMessage: "Por favor, inicia sesión para acceder a esta función.",
  chatbot: "MediBot",
} as const;

export default es;
