import { typeLanguages } from "./typesTranslations";

const es: typeLanguages = {
  addMedication: "Agregar medicamento",
  addPatient: "Agregar Paciente",
  addPatientForm: "Aquí estaría el formulario para agregar un paciente",
  capsysDescription:
    "El pastillero inteligente es un dispositivo conectado diseñado para facilitar la gestión diaria de medicamentos. Se sincroniza con nuestra app móvil para enviar recordatorios automáticos, alertas personalizadas y notificaciones en tiempo real. Gracias a su diseño funcional y tecnología integrada, permite a cuidadores y usuarios llevar un control preciso y sin errores sobre horarios, dosis y administración, mejorando la adherencia al tratamiento y la tranquilidad en el cuidado",
  close: "Cerrar",
  dearUser: "querido usuario",
  email: "Correo electrónico",
  error: "Error",
  errorSignUp: "Error al registrarse, por favor intente más tarde.",
  friday: "Viernes",
  greeting: "Hola, Usuario Administrador",
  headerTitle: "Encabezado",
  languages: "Lenguajes",
  logOut: "Cerrar sesión",
  login: "Iniciar sesión",
  menuHome: "Inicio",
  menuLogout: "Cerrar sesión",
  menuProfile: "Perfil",
  monday: "Lunes",
  more: "más",
  noMedications: "Sin medicamentos",
  notLoggedIn: "No has iniciado sesión.",
  password: "Contraseña",
  patientDescription: "Descripción del paciente",
  patientName: "Nombre del paciente",
  rememberMe: "Recuérdame",
  saturday: "Sábado",
  signUp: "Registrarse",
  success: "Éxito",
  successSignUp: "Registro exitoso.",
  successSignUpMessage: "Ahora puedes iniciar sesión con tus credenciales.",
  sunday: "Domingo",
  thursday: "Jueves",
  tuesday: "Martes",
  verifyEmail:
    "Hemos enviado un correo de verificación a tu dirección. Por favor, revisa tu bandeja de entrada y verifica tu correo para completar el proceso de registro.",
  wednesday: "Miércoles",
  welcome: "Bienvenido",
  welcomeUser: "Bienvenido, {{name}}!",
  emailPlaceholder: "Correo electrónico",
  passwordPlaceholder: "Contraseña",
  loginButton: "Iniciar Sesión",
  forgotPassword: "¿Olvidaste tu contraseña?",
  createAccount: "Crear nueva cuenta",
  errorEmpty: "Por favor complete todos los campos",
  errorEmail: "Ingrese un email válido",
  errorPassword:
    "La contraseña debe tener al menos 8 caracteres y contener letras y números",
  hasAccount: "¿Ya tienes una cuenta? Inicia sesión",
  errorNoSession: "No se recibieron datos de sesión",
  errorNoSessionMessage:
    "Por favor, intenta iniciar sesión nuevamente o contacta al soporte si el problema persiste.",
  successLogout: "Sesión cerrada exitosamente",
  successLogoutMessage: "Has cerrado sesión correctamente. ¡Hasta luego!",
  age: "Edad",
  years: "años",
  patientText: "Paciente",
  medicationText: "Medicamento",
  dosage: "Dosis",
  dosagePlaceholder: " Dosis (ej. {0})",
  noNameGiven: "No se proporcionó un nombre",
  conditions: "Condiciones",
  allergies: "Alergias",
  name: "Nombre",
  medicationsManagement: "Gestión de Medicamentos",
  type: "Tipo",
  daysText: "Días",
  selectTime: "Seleccionar Hora",
  addSchedule: "Agregar Horario",
  schedulesScheduled: "Horarios programados",
  schedulesNotScheduled: "Horarios no programados",
  addMedicationsOnTop: "Agrega medicamentos usando el formulario superior",
  hour: "Hora",
  days: {
    monday: "Lu",
    tuesday: "Ma",
    wednesday: "Mi",
    thursday: "Ju",
    friday: "Vi",
    saturday: "Sa",
    sunday: "Do",
  },
  dosageTypes: JSON.stringify(["pastillas", "mg", "unidades"]),
  urgency: JSON.stringify({ low: "Baja", medium: "Media", high: "Alta" }),
  unknown: "Desconocido",
  medicationPlaceholder: "P. ej. Loratadina",
  clearMedication: "Limpiar Medicamento",
  deleteMedication: "Eliminar Medicamento",
  intervalHours: "Horas de intervalo",
  intervalHoursPlaceholder: "Horas de intervalo (ej. 8)",
  stock: "Stock",
  stockPlaceholder: "Ej. 30",
  urgencyText: "Urgencia",
  namePatient: "Nombre: {{interpolateMessage}}",
  // User Settings Component
  settings: "Ajustes",
  save: "Guardar",
  enableNotifications: "Activar notificaciones",
  uploadImage: "Subir imagen",
  description: "Descripción",
  caregiver: "Cuidador",
  patient: "Paciente",
  both: "Ambos",
  fullName: "Nombre completo",
  numberPhone: "Número de teléfono",
  userImage: "Imagen de usuario",
  noImage: "Sin imagen",
  role: "Rol",

  
  nameRequired: "El nombre es obligatorio",
  phoneRequired: "El número de teléfono es obligatorio",
  phoneFormatError: "El número de teléfono debe tener 10 dígitos",
  dataUpdated: "Datos actualizados correctamente",
  errorUserImage: "Error al subir la imagen del usuario",
  errorIdUser: "Error al obtener el identificador del usuario",
  imageUploadSuccess: "Imagen subida correctamente",
  dashboard: "Panel de usuario",
  home: "Inicio",
  pillboxSettings: "Configuración del pastillero",
  pillboxDescription:
    "En esta sección puedes configurar tu pastillero siguiendo las indicaciones proporcionadas por Capsy. Asegúrate de colocar cada medicamento en el compartimento correspondiente y verifica que esté ubicado correctamente.",
} as const;

export default es;
