import { StyleSheet } from "react-native";
import { useResponsiveLayout } from "@context/LayoutContext";
import { useMemo } from "react";

export const useStylesScheduleMedication = () => {
  const { isPhone, isWeb, width, height } = useResponsiveLayout();

  const styles = useMemo(() => StyleSheet.create({
    screenContainer: {
      flex: 1,
      backgroundColor: "#ecebea",
    },
    container: {
      flex: 1,
      backgroundColor: "#ecebea",
    },
    content: {
      flexGrow: 1,
      paddingHorizontal: 16,
      paddingTop: isPhone ? 24 : 20, 
      paddingBottom: isPhone ? 100 : 16, 
      backgroundColor: "#ecebea",
    },
    pageHeader: {
      backgroundColor: "transparent",
      marginBottom: 28,
      paddingHorizontal: 8,
      marginRight: isPhone ? 60 : 0, 
      marginLeft: isPhone ? 8 : 60,
    },
    pageTitle: {
      fontSize: isPhone ? 28 : 36,
      fontWeight: "800",
      color: "#00a69d",
      textAlign: "center",
      marginBottom: 12,
      textShadowColor: "rgba(0, 166, 157, 0.3)",
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 4,
      letterSpacing: isPhone ? 0.5 : 1,
    },
    pageSubtitle: {
      fontSize: isPhone ? 14 : 16,
      color: "#21aae1",
      textAlign: "center",
      lineHeight: 22,
      fontWeight: "500",
    },
    header: {
      marginBottom: 24,
      backgroundColor: "#fff",
      borderRadius: 20,
      padding: isPhone ? 20 : 24,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 8,
      borderWidth: 1,
      borderColor: "rgba(0, 166, 157, 0.1)",
      maxWidth: isPhone ? "100%" : 600,
      alignSelf: "center",
      width: "100%",
    },
    patientSelector: {
      marginBottom: 16,
    },
    patientLabel: {
      fontSize: 18,
      fontWeight: "700",
      color: "#00a69d",
      marginBottom: 12,
      textShadowColor: "rgba(0, 166, 157, 0.1)",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    patientButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    patientButton: {
      backgroundColor: "rgba(124, 206, 212, 0.9)",
      paddingVertical: 14,
      paddingHorizontal: 22,
      borderRadius: 28,
      shadowColor: "#7cced4",
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 6,
      elevation: 4,
      borderWidth: 1,
      borderColor: "rgba(124, 206, 212, 0.4)",
      minWidth: isPhone ? "auto" : 120,
      width: isPhone ? "auto" : 120,
      height: isPhone ? "auto" : 44,
      justifyContent: "center",
      alignItems: "center",
    },
    selectedPatient: {
      backgroundColor: "#00a69d",
      shadowColor: "#00a69d",
      shadowOpacity: 0.4,
      borderColor: "#00a69d",
      transform: [{ scale: 1.08 }],
      shadowOffset: { width: 0, height: 4 },
      shadowRadius: 8,
      elevation: 6,
    },
    patientButtonText: {
      color: "#00a69d",
      fontWeight: "600",
      fontSize: 14,
    },
    selectedPatientText: {
      color: "white",
      fontWeight: "700",
      fontSize: 14,
    },
    patientInfo: {
      backgroundColor: "rgba(236, 235, 234, 0.8)",
      borderRadius: 12,
      padding: 16,
      marginTop: 12,
      borderWidth: 1,
      borderColor: "rgba(33, 170, 225, 0.2)",
    },
    patientDetail: {
      fontSize: 15,
      color: "#21aae1",
      marginBottom: 6,
      fontWeight: "500",
    },
    formContainer: {
      backgroundColor: "#fff",
      borderRadius: 24,
      padding: isPhone ? 24 : 28,
      marginBottom: 28,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.18,
      shadowRadius: 20,
      elevation: 10,
      borderWidth: 1,
      borderColor: "rgba(0, 166, 157, 0.08)",
      maxWidth: isPhone ? "100%" : 600,
      alignSelf: "center",
      width: "100%",
    },
    formContent: {
      paddingBottom: 20,
      // Remove flex: 1 to let content determine its height
    },
    inputGroup: {
      marginBottom: isPhone ? 20 : 24,
    },
    label: {
      fontWeight: "700",
      marginBottom: 12,
      color: "#00a69d",
      fontSize: 16,
      textShadowColor: "rgba(0, 166, 157, 0.1)",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    medicationScroll: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      maxHeight: isPhone ? 120 : 80,
      marginTop: 12, 
    },
    medicationButtons: {
      flexDirection: "row",
      gap: 12,
    },
    medButton: {
      backgroundColor: "#ecebea",
      paddingVertical: 10,
      paddingHorizontal: 18,
      borderRadius: 12,
      minWidth: isPhone ? 100 : 120,
      width: isPhone ? "auto" : 120,
      height: isPhone ? "auto" : 40,
      alignItems: "center",
      justifyContent: "center",
    },
    selectedMedButton: {
      backgroundColor: "#ffffff",
      borderWidth: 2,
      borderColor: "#00a69d",
      borderRadius: 16,
      padding: 16,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 6,
      marginVertical: 8,
    },
    medButtonText: {
      color: "#00a69d",
      fontWeight: "500",
    },
    selectedMedText: {
      color: "white",
      fontWeight: "600",
    },
    doseContainer: {
      flexDirection: isPhone ? "column" : "row",
      justifyContent: "space-between",
      gap: 16,
      marginBottom: isPhone ? 20 : 24,
    },
    doseInputGroup: {
      flex: 1,
    },
    dosageTypeGroup: {
      flex: 1,
    },
    input: {
      width: "100%",
      fontSize: isPhone ? 14 : 15,
      backgroundColor: "#ecebea",
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      borderBottomWidth: 2,
      borderBottomColor: "#00a69d",
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
      minHeight: isPhone ? 56 : 58,
    },
    inputError: {
      borderBottomColor: "#ff6b6b",
      borderBottomWidth: 3,
      shadowColor: "#ff6b6b",
      backgroundColor: "#fff5f5",
    },
    labelError: {
      color: "#ff6b6b",
    },
    requiredIndicator: {
      color: "#ffffff",
      backgroundColor: "#dc3545",
      fontSize: 20,
      fontWeight: "900",
      marginLeft: 8,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 12,
      lineHeight: 20,
      includeFontPadding: false,
      textAlign: 'center',
      minWidth: 24,
      textAlignVertical: 'center',
    },
    errorText: {
      color: "#ff6b6b",
      fontSize: 12,
      marginTop: 4,
      fontStyle: "italic",
    },
    validationSummary: {
      backgroundColor: "#fff5f5",
      borderWidth: 2,
      borderColor: "#ff6b6b",
      borderRadius: 12,
      padding: 16,
      marginVertical: 16,
      shadowColor: "#ff6b6b",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    validationTitle: {
      color: "#ff6b6b",
      fontSize: 16,
      fontWeight: "bold",
      marginBottom: 8,
      textAlign: "center",
    },
    validationMessage: {
      color: "#ff6b6b",
      fontSize: 14,
      marginBottom: 12,
      textAlign: "center",
    },
    validationList: {
      paddingLeft: 8,
    },
    validationItem: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: 4,
    },
    validationBullet: {
      color: "#ff6b6b",
      fontSize: 16,
      fontWeight: "bold",
      marginRight: 8,
    },
    validationItemText: {
      color: "#ff6b6b",
      fontSize: 14,
      flex: 1,
    },
    medicationText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#00a69d",
      marginBottom: 8,
    },
    dosageButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 4,
    },
    dosageButton: {
      backgroundColor: "#ecebea",
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 12,
      minWidth: isPhone ? "auto" : 80,
      width: isPhone ? "auto" : 80,
      height: isPhone ? "auto" : 36,
      justifyContent: "center",
      alignItems: "center",
    },
    dosageButtonError: {
      borderWidth: 2,
      borderColor: "#ff6b6b",
      backgroundColor: "#fff5f5",
    },
    selectedDosageButton: {
      backgroundColor: "#00a69d",
    },
    dosageButtonText: {
      color: "#00a69d",
      fontSize: 14,
    },
    selectedDosageText: {
      color: "white",
      fontWeight: "600",
      fontSize: 14,
    },
    daysContainer: {
      flexDirection: "row",
      justifyContent: isPhone ? "space-around" : "space-between",
      flexWrap: isPhone ? "wrap" : "nowrap",
      gap: isPhone ? 8 : 0,
    },
    dayButton: {
      width: isPhone ? 38 : 42,
      height: isPhone ? 38 : 42,
      borderRadius: isPhone ? 19 : 21,
      backgroundColor: "#ecebea",
      justifyContent: "center",
      alignItems: "center",
    },
    dayButtonError: {
      borderWidth: 2,
      borderColor: "#ff6b6b",
      backgroundColor: "#fff5f5",
    },
    selectedDay: {
      backgroundColor: "#00a69d",
    },
    dayButtonText: {
      color: "#00a69d",
      fontWeight: "500",
      fontSize: 14,
    },
    selectedDayText: {
      color: "white",
      fontWeight: "600",
      fontSize: 14,
    },
    timeButton: {
      width: "100%",
      fontSize: 14,
      backgroundColor: "#ecebea",
      borderRadius: 16,
      padding: 16,
      color: "#333333",
      borderWidth: 0,
      borderBottomWidth: 2,
      borderBottomColor: "#00a69d",
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      boxShadow: "0 2px 4px rgba(0, 166, 157, 0.1)",
      minHeight: 56,
      paddingTop: 20,
      paddingBottom: 12,
    },
    timeButtonError: {
      borderBottomColor: "#ff6b6b",
      borderBottomWidth: 3,
      backgroundColor: "#fff5f5",
      boxShadow: "0 2px 4px rgba(255, 107, 107, 0.1)",
    },
    timeButtonText: {
      fontSize: 16,
      color: "#00a69d",
      textAlign: "center",
    },
    addButton: {
      backgroundColor: "#00a69d",
      padding: isPhone ? 18 : 20,
      borderRadius: 16,
      alignItems: "center",
      marginTop: 16,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 6,
      borderWidth: 1,
      borderColor: "rgba(255, 255, 255, 0.2)",
    },
    addButtonDisabled: {
      backgroundColor: "#cccccc",
      shadowColor: "#cccccc",
      shadowOpacity: 0.1,
    },
    medicationButton: {
      backgroundColor: "#ecebea",
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 12,
      marginHorizontal: 5,
      marginVertical: 4,
      minWidth: isPhone ? 120 : 140,
      width: isPhone ? "auto" : 140,
      height: isPhone ? "auto" : 36,
      alignItems: "center",
      justifyContent: "center",
    },
    medicationButtonText: {
      color: "#00a69d",
      fontSize: 14,
      fontWeight: "500",
    },
    addButtonText: {
      color: "white",
      fontWeight: "700",
      fontSize: isPhone ? 16 : 17,
    },
    addButtonTextDisabled: {
      color: "#888888",
    },
    schedulesContainer: {
      backgroundColor: "#fff",
      borderRadius: 20,
      padding: isPhone ? 20 : 24,
      flex: 1 / 3,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 6,
      maxWidth: isPhone ? "100%" : 600,
      alignSelf: "center",
      width: "100%",
      marginBottom: isPhone ? 24 : 0,
      borderWidth: 1,
      borderColor: "rgba(0, 166, 157, 0.05)",
    },
    schedulesContent: {
      flex: 1,
      paddingBottom: 20,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: "700",
      marginBottom: 16,
      color: "#00a69d",
    },
    scheduleList: {
      paddingBottom: 20,
    },
    scheduleItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 18,
      paddingHorizontal: 4,
      borderBottomWidth: 1,
      borderBottomColor: "rgba(124, 206, 212, 0.3)",
      alignItems: "center",
      backgroundColor: "rgba(236, 235, 234, 0.3)",
      borderRadius: 12,
      marginVertical: 4,
    },
    scheduleInfo: {
      flex: 1,
      marginRight: 12,
    },
    medName: {
      fontWeight: "600",
      fontSize: 17,
      marginBottom: 6,
      color: "#00a69d",
    },
    doseText: {
      fontSize: 15,
      color: "#21aae1",
    },
    requiredDosesText: {
      fontSize: 13,
      color: "#666",
      marginTop: 2,
      fontStyle: "italic",
    },
    daysIndicator: {
      flexDirection: "row",
      minWidth: 160,
      justifyContent: "space-between",
    },
    dayIndicator: {
      fontSize: 15,
      color: "#60c4b4",
      fontWeight: "600",
    },
    activeDayIndicator: {
      color: "#00a69d",
    },
    deleteButton: {
      backgroundColor: "#fce8e6",
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 10,
    },
    deleteButtonText: {
      color: "#d93025",
      fontSize: 18,
      fontWeight: "bold",
    },
    clearMedicationButton: {
      backgroundColor: "#fce8e6",
      padding: 12,
      borderRadius: 12,
      alignItems: "center",
      marginTop: 16,
    },
    selectedMedication: {
      backgroundColor: "#00a69d",
      padding: 12,
      borderRadius: 12,
      alignItems: "center",
      marginTop: 16,
      justifyContent: "center",
      flexDirection: "column",
      gap: 8,
    },
    clearMedicationChildren: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
      paddingHorizontal: 4,
    },
    clearMedicationText: {
      color: "#00a69d",
      fontWeight: "600",
      fontSize: 16,
      flex: 1,
      textAlign: "center",
      marginHorizontal: 8,
    },
    closeButton: {
      backgroundColor: "#ff6b6b",
      borderRadius: 20,
      width: 32,
      height: 32,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#ff6b6b",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 3,
    },
    closeButtonText: {
      color: "#ffffff",
      fontSize: 18,
      fontWeight: "bold",
      lineHeight: 18,
    },
    medicationIcon: {
      backgroundColor: "#e8f7f6",
      borderRadius: 20,
      width: 32,
      height: 32,
      justifyContent: "center",
      alignItems: "center",
    },
    urgencyButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 4,
    },
    urgencyButton: {
      backgroundColor: "#ecebea",
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 12,
      minWidth: isPhone ? "auto" : 80,
      width: isPhone ? "auto" : 80,
      height: isPhone ? "auto" : 36,
      justifyContent: "center",
      alignItems: "center",
    },
    urgencyButtonError: {
      borderWidth: 2,
      borderColor: "#ff6b6b",
      backgroundColor: "#fff5f5",
    },
    selectedUrgencyButton: {
      backgroundColor: "#00a69d",
    },
    urgencyButtonText: {
      color: "#00a69d",
      fontSize: 14,
    },
    selectedUrgencyText: {
      color: "white",
      fontWeight: "600",
      fontSize: 14,
    },
    emptyState: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 40,
    },
    emptyStateText: {
      fontSize: 18,
      color: "#60c4b4",
      fontWeight: "500",
      marginBottom: 8,
    },
    emptyStateSubtext: {
      fontSize: 14,
      color: "#21aae1",
      textAlign: "center",
    },
    backButton: {
      position: 'absolute',
      top: isPhone ? 85 : 85,
      right: isPhone ? 16 : undefined, 
      left: isPhone ? undefined : 16,
      zIndex: 998, 
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: isPhone ? '#00a69d' : 'transparent',
      paddingHorizontal: isPhone ? 12 : 8,
      paddingVertical: isPhone ? 12 : 8,
      borderRadius: isPhone ? 25 : 0,
      shadowColor: isPhone ? '#00a69d' : 'transparent',
      shadowOffset: isPhone ? { width: 0, height: 4 } : { width: 0, height: 0 },
      shadowOpacity: isPhone ? 0.2 : 0,
      shadowRadius: isPhone ? 8 : 0,
      elevation: 0, 
      width: isPhone ? 50 : 40,
      height: isPhone ? 50 : 40,
      borderWidth: isPhone ? 1 : 0,
      borderColor: isPhone ? 'rgba(255, 255, 255, 0.2)' : 'transparent',
    },
  }), [isPhone]); 

  return {
    styles,
    isPhone,
    isWeb,
    width,
    height,
  };
};
