import { StyleSheet } from "react-native";
import { useResponsiveLayout } from "@context/LayoutContext";

export const useStylesScheduleMedication = () => {
  // Add missing styles for errorContainer and inputDescription
  const errorContainer = {
    backgroundColor: '#ffebee',
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: '#e53935',
  };
  const inputDescription = {
    color: '#21aae1',
    fontSize: 13,
    marginTop: 4,
    marginLeft: 2,
  };
  const { isPhone, isWeb, width, height } = useResponsiveLayout();

  const styles = StyleSheet.create({
    inputHint: {
      color: '#21aae1',
      fontSize: 13,
      marginBottom: 2,
      marginLeft: 2,
    },
    errorContainer,
    inputDescription,
    validationSummary: {
      backgroundColor: '#ffebee',
      borderRadius: 12,
      padding: 14,
      marginTop: 8,
      marginBottom: 8,
      borderWidth: 1.5,
      borderColor: '#e53935',
    },
    validationTitle: {
      color: '#e53935',
      fontWeight: 'bold',
      fontSize: 16,
      marginBottom: 2,
    },
    validationMessage: {
      color: '#e53935',
      fontSize: 14,
      marginBottom: 6,
    },
    validationList: {
      marginLeft: 8,
    },
    validationItem: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 2,
    },
    validationBullet: {
      color: '#e53935',
      fontWeight: 'bold',
      marginRight: 4,
    },
    validationItemText: {
      color: '#e53935',
      fontSize: 13,
    },
    addButtonDisabled: {
      backgroundColor: '#b2dfdb',
    },
    addButtonTextDisabled: {
      color: '#fff',
      opacity: 0.6,
    },
    labelError: {
      color: '#e53935',
      fontWeight: 'bold',
    },
    requiredIndicator: {
      color: '#e53935',
      fontWeight: 'bold',
      marginLeft: 2,
    },
    inputError: {
      borderColor: '#e53935',
      backgroundColor: '#ffebee',
    },
    medSearchScroll: {
      marginTop: 8,
      marginBottom: 4,
      minHeight: 40,
      maxHeight: 48,
    },
    errorText: {
      color: '#e53935',
      fontSize: 13,
      marginTop: 2,
      marginLeft: 2,
    },
    container: {
      flex: 1,
      backgroundColor: "#f4f4f4",
      padding: 16,
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 16,
      backgroundColor: "#f4f4f4",
    },
    header: {
      marginBottom: 20,
      backgroundColor: "#fff",
      borderRadius: 12,
      padding: 16,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 4,
    },
    title: {
      fontSize: 24,
      fontWeight: "700",
      color: "#00a69d",
      marginBottom: 12,
    },
    patientSelector: {
      marginBottom: 12,
    },
    patientLabel: {
      fontSize: 16,
      fontWeight: "600",
      color: "#21aae1",
      marginBottom: 8,
    },
    patientButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
    },
    patientButton: {
      backgroundColor: "#fff",
      paddingVertical: 10,
      paddingHorizontal: 18,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: "#00a69d",
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 6,
      elevation: 2,
    },
    selectedPatient: {
      backgroundColor: "#00a69d",
      borderColor: "#21aae1",
      borderWidth: 2,
    },
    patientButtonText: {
      color: "#00a69d",
      fontWeight: "700",
      fontSize: 16,
      letterSpacing: 0.2,
    },
    selectedPatientText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 16,
      letterSpacing: 0.2,
    },
    patientInfo: {
      backgroundColor: "#f4f4f4",
      borderRadius: 8,
      padding: 12,
      marginTop: 8,
    },
    patientDetail: {
      fontSize: 14,
      color: "#21aae1",
      marginBottom: 4,
    },
    formContainer: {
      backgroundColor: "#fff",
      borderRadius: 24,
      maxWidth: 500,
      width: '100%',
      alignSelf: 'center',
      flex: 1,
      padding: 28,
      marginBottom: 28,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.14,
      shadowRadius: 18,
      elevation: 8,
      borderWidth: 1.5,
      borderColor: "#00a69d22",
    },
    // Puedes ajustar el ancho máximo del campo Select Time aquí:
    timeInputContainer: {
      width: '100%',
      maxWidth: 100, // <-- Ajusta este valor para el campo Select Time
      alignSelf: 'center',
    },
    formContent: {
      flex: 1,
      paddingBottom: 20,
    },
    inputGroup: {
      marginBottom: 28,
    },
    label: {
      fontWeight: "600",
      marginBottom: 10,
      color: "#00a69d",
      fontSize: 16,
    },
    medicationScroll: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      flex: 1,
    },
    medicationButtons: {
      flexDirection: "row",
      gap: 12,
    },
    medButton: {
      backgroundColor: "#fff",
      paddingVertical: 12,
      paddingHorizontal: 22,
      borderRadius: 18,
      minWidth: 110,
      alignItems: "center",
      borderWidth: 1.5,
      borderColor: "#00a69d",
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 6,
      elevation: 2,
    },
    selectedMedButton: {
      backgroundColor: "#00a69d",
      paddingVertical: 12,
      paddingHorizontal: 22,
      borderRadius: 18,
      minWidth: 110,
      alignItems: "center",
      borderWidth: 1.5,
      borderColor: "#21aae1",
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 6,
      elevation: 2,
    },
    medButtonText: {
      color: "#00a69d",
      fontWeight: "700",
      fontSize: 16,
      letterSpacing: 0.2,
    },
    selectedMedText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 16,
      letterSpacing: 0.2,
    },
    doseContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      gap: 28,
      marginBottom: 28,
    },
    doseInputGroup: {
      flex: 1,
    },
    dosageTypeGroup: {
      flex: 1,
    },
    input: {
      width: "100%",
      fontSize: 17,
      backgroundColor: "#fff",
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: "#00a69d",
      paddingHorizontal: 18,
      paddingVertical: 14,
      color: "#00a69d",
      fontWeight: "600",
      letterSpacing: 0.2,
    },
    medicationText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#00a69d",
      marginBottom: 8,
    },
    dosageButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 4,
    },
    dosageButton: {
      backgroundColor: "#ecebea",
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 12,
    },
    selectedDosageButton: {
      backgroundColor: "#00a69d",
    },
    dosageButtonText: {
      color: "#00a69d",
      fontSize: 14,
    },
    selectedDosageText: {
      color: "white",
      fontWeight: "600",
      fontSize: 14,
      letterSpacing: 0.2,
    },
    daysContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
    },
    dayButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: "#fff",
      justifyContent: "center",
      alignItems: "center",
      borderWidth: 1.5,
      borderColor: "#00a69d",
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 6,
      elevation: 2,
    },
    selectedDay: {
      backgroundColor: "#00a69d",
      borderColor: "#21aae1",
      borderWidth: 2,
    },
    dayButtonText: {
      color: "#00a69d",
      fontWeight: "700",
      fontSize: 16,
      letterSpacing: 0.2,
    },
    selectedDayText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 16,
      letterSpacing: 0.2,
    },
    timeButton: {
      borderWidth: 1.5,
      borderColor: "#00a69d",
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 24,
      backgroundColor: "#fff",
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 6,
      elevation: 2,
      maxWidth: 100
    },
    timeButtonText: {
      fontSize: 17,
      color: "#00a69d",
      textAlign: "center",
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    addButton: {
      backgroundColor: "#00a69d",
      padding: 16,
      borderRadius: 12,
      alignItems: "center",
      marginTop: 8,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    addButtonText: {
      color: "white",
      fontWeight: "700",
      fontSize: 16,
    },
    schedulesContainer: {
      backgroundColor: "#fff",
      borderRadius: 24,
      padding: 24,
      flex: 1 / 3,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.14,
      shadowRadius: 18,
      elevation: 8,
      borderWidth: 1.5,
      borderColor: "#00a69d22",
    },
    schedulesContent: {
      flex: 1,
      paddingBottom: 20,
    },
    sectionTitle: {
      fontSize: 22,
      fontWeight: "800",
      marginBottom: 20,
      color: "#00a69d",
      letterSpacing: 0.3,
      textShadowColor: "#00a69d22",
      textShadowOffset: { width: 1, height: 2 },
      textShadowRadius: 4,
    },
    scheduleList: {
      paddingBottom: 24,
      marginTop: 8,
    },
    scheduleItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 18,
      borderBottomWidth: 2,
      borderBottomColor: "#00a69d22",
      alignItems: "center",
      marginBottom: 2,
    },
    scheduleInfo: {
      flex: 1,
      marginRight: 18,
    },
    medName: {
      fontWeight: "800",
      fontSize: 18,
      marginBottom: 4,
      color: "#00a69d",
      letterSpacing: 0.2,
    },
    doseText: {
      fontSize: 16,
      color: "#21aae1",
      fontWeight: "700",
    },
    daysIndicator: {
      flexDirection: "row",
      minWidth: 180,
      justifyContent: "space-between",
      marginTop: 2,
    },
    dayIndicator: {
      fontSize: 15,
      color: "#60c4b4",
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    activeDayIndicator: {
      color: "#00a69d",
      fontWeight: "800",
    },
    deleteButton: {
      backgroundColor: "#fce8e6",
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 10,
      borderWidth: 1.5,
      borderColor: "#e74c3c55",
      shadowColor: "#e74c3c",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 6,
      elevation: 2,
    },
    deleteButtonText: {
      color: "#d93025",
      fontSize: 18,
      fontWeight: "bold",
    },
    clearMedicationButton: {
      backgroundColor: "#fce8e6",
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderRadius: 16,
      alignItems: "center",
      marginTop: 20,
      borderWidth: 1.5,
      borderColor: "#e74c3c55",
    },
    clearMedicationChildren: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-evenly",
      gap: 8,
    },
    selectedMedication: {
      backgroundColor: "#00a69d",
      paddingVertical: 18,
      paddingHorizontal: 32,
      borderRadius: 18,
      marginTop: 16,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.22,
      shadowRadius: 10,
      elevation: 6,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-evenly",
      gap: 8,
    },
    clearMedicationText: {
      color: "white",
      fontWeight: "600",
      fontSize: 16,
    },
    urgencyButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 4,
    },
    urgencyButton: {
      backgroundColor: "#ecebea",
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 12,
    },
    selectedUrgencyButton: {
      backgroundColor: "#00a69d",
    },
    urgencyButtonText: {
      color: "#00a69d",
      fontSize: 14,
    },
    selectedUrgencyText: {
      color: "white",
      fontWeight: "600",
      fontSize: 14,
    },
    emptyState: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 48,
      backgroundColor: "#fff",
      borderRadius: 18,
      marginVertical: 24,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    emptyStateText: {
      fontSize: 20,
      color: "#00a69d",
      fontWeight: "700",
      marginBottom: 10,
      textAlign: "center",
    },
    emptyStateSubtext: {
      fontSize: 15,
      color: "#21aae1",
      textAlign: "center",
      marginTop: 2,
    },

    backButton: {
      position: "absolute",
      left: 18,
      top: 80,
      zIndex: 10,
      backgroundColor: "#e6f9f7",
      borderRadius: 50,
      width: 44,
      height: 44,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: "#00a69d",
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 3,
    },
  });

  return {
    styles: {
      ...styles,
      labelError: styles.labelError,
      requiredIndicator: styles.requiredIndicator,
      inputError: styles.inputError,
      medSearchScroll: styles.medSearchScroll,
      errorText: styles.errorText,
      inputHint: styles.inputHint,
      validationSummary: styles.validationSummary,
      validationTitle: styles.validationTitle,
      validationMessage: styles.validationMessage,
      validationList: styles.validationList,
      validationItem: styles.validationItem,
      validationBullet: styles.validationBullet,
      validationItemText: styles.validationItemText,
      addButtonDisabled: styles.addButtonDisabled,
      addButtonTextDisabled: styles.addButtonTextDisabled,
    },
    isPhone,
    isWeb,
    width,
    height,
  };
};
