import { StyleSheet } from "react-native";
import { useResponsiveLayout } from "@context/LayoutContext";
import { useMemo } from "react";

export const useStylesScheduleMedication = () => {
  const { isPhone, isWeb, width, height } = useResponsiveLayout();

  const styles = useMemo(() => StyleSheet.create({
    screenContainer: {
      flex: 1,
      backgroundColor: "#ecebea",
    },
    container: {
      flex: 1,
      backgroundColor: "#ecebea",
    },
    content: {
      flexGrow: 1,
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: isPhone ? 100 : 16, // Add extra bottom padding for mobile
      backgroundColor: "#ecebea",
    },
    pageHeader: {
      backgroundColor: "transparent",
      marginBottom: 24,
      paddingHorizontal: 8,
    },
    pageTitle: {
      fontSize: isPhone ? 26 : 32,
      fontWeight: "800",
      color: "#00a69d",
      textAlign: "center",
      marginBottom: 8,
      textShadowColor: "rgba(0, 166, 157, 0.2)",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 3,
    },
    pageSubtitle: {
      fontSize: isPhone ? 14 : 16,
      color: "#21aae1",
      textAlign: "center",
      lineHeight: 22,
      fontWeight: "500",
    },
    header: {
      marginBottom: 20,
      backgroundColor: "#fff",
      borderRadius: 16,
      padding: 20,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 8,
      elevation: 6,
      borderWidth: 1,
      borderColor: "rgba(0, 166, 157, 0.1)",
    },
    patientSelector: {
      marginBottom: 16,
    },
    patientLabel: {
      fontSize: 18,
      fontWeight: "700",
      color: "#00a69d",
      marginBottom: 12,
      textShadowColor: "rgba(0, 166, 157, 0.1)",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    patientButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
    },
    patientButton: {
      backgroundColor: "rgba(124, 206, 212, 0.8)",
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 25,
      shadowColor: "#7cced4",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.15,
      shadowRadius: 4,
      elevation: 3,
      borderWidth: 1,
      borderColor: "rgba(124, 206, 212, 0.3)",
    },
    selectedPatient: {
      backgroundColor: "#00a69d",
      shadowColor: "#00a69d",
      shadowOpacity: 0.3,
      borderColor: "#00a69d",
      transform: [{ scale: 1.05 }],
    },
    patientButtonText: {
      color: "#00a69d",
      fontWeight: "600",
      fontSize: 14,
    },
    selectedPatientText: {
      color: "white",
      fontWeight: "700",
      fontSize: 14,
    },
    patientInfo: {
      backgroundColor: "rgba(236, 235, 234, 0.8)",
      borderRadius: 12,
      padding: 16,
      marginTop: 12,
      borderWidth: 1,
      borderColor: "rgba(33, 170, 225, 0.2)",
    },
    patientDetail: {
      fontSize: 15,
      color: "#21aae1",
      marginBottom: 6,
      fontWeight: "500",
    },
    formContainer: {
      backgroundColor: "#fff",
      borderRadius: 20,
      padding: 20,
      marginBottom: 20,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.15,
      shadowRadius: 12,
      elevation: 8,
      borderWidth: 2,
      borderColor: "rgba(0, 166, 157, 0.1)",
    },
    formContent: {
      paddingBottom: 20,
      // Remove flex: 1 to let content determine its height
    },
    inputGroup: {
      marginBottom: isPhone ? 20 : 24,
    },
    label: {
      fontWeight: "700",
      marginBottom: 12,
      color: "#00a69d",
      fontSize: 16,
      textShadowColor: "rgba(0, 166, 157, 0.1)",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
    },
    medicationScroll: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      maxHeight: isPhone ? 120 : 80, // Limit height on mobile for better visibility
    },
    medicationButtons: {
      flexDirection: "row",
      gap: 12,
    },
    medButton: {
      backgroundColor: "#ecebea",
      paddingVertical: 10,
      paddingHorizontal: 18,
      borderRadius: 12,
      minWidth: 100,
      alignItems: "center",
    },
    selectedMedButton: {
      backgroundColor: "#00a69d",
      padding: 10,
      borderRadius: 12,
    },
    medButtonText: {
      color: "#00a69d",
      fontWeight: "500",
    },
    selectedMedText: {
      color: "white",
      fontWeight: "600",
    },
    doseContainer: {
      flexDirection: isPhone ? "column" : "row",
      justifyContent: "space-between",
      gap: 16,
      marginBottom: isPhone ? 20 : 24,
    },
    doseInputGroup: {
      flex: 1,
    },
    dosageTypeGroup: {
      flex: 1,
    },
    input: {
      width: "100%",
      fontSize: 14,
      backgroundColor: "#ecebea",
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      borderBottomWidth: 2,
      borderBottomColor: "#00a69d",
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
      minHeight: 56,
    },
    medicationText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#00a69d",
      marginBottom: 8,
    },
    dosageButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 4,
    },
    dosageButton: {
      backgroundColor: "#ecebea",
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 12,
    },
    selectedDosageButton: {
      backgroundColor: "#00a69d",
    },
    dosageButtonText: {
      color: "#00a69d",
      fontSize: 14,
    },
    selectedDosageText: {
      color: "white",
      fontWeight: "600",
      fontSize: 14,
    },
    daysContainer: {
      flexDirection: "row",
      justifyContent: isPhone ? "space-around" : "space-between",
      flexWrap: isPhone ? "wrap" : "nowrap",
      gap: isPhone ? 8 : 0,
    },
    dayButton: {
      width: isPhone ? 38 : 42,
      height: isPhone ? 38 : 42,
      borderRadius: isPhone ? 19 : 21,
      backgroundColor: "#ecebea",
      justifyContent: "center",
      alignItems: "center",
    },
    selectedDay: {
      backgroundColor: "#00a69d",
    },
    dayButtonText: {
      color: "#00a69d",
      fontWeight: "500",
      fontSize: 14,
    },
    selectedDayText: {
      color: "white",
      fontWeight: "600",
      fontSize: 14,
    },
    timeButton: {
      width: "100%",
      fontSize: 14,
      backgroundColor: "#ecebea",
      borderRadius: 16,
      padding: 16,
      color: "#333333",
      borderWidth: 0,
      borderBottomWidth: 2,
      borderBottomColor: "#00a69d",
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      borderBottomLeftRadius: 16,
      borderBottomRightRadius: 16,
      boxShadow: "0 2px 4px rgba(0, 166, 157, 0.1)",
      minHeight: 56,
      paddingTop: 20,
      paddingBottom: 12,
    },
    timeButtonText: {
      fontSize: 16,
      color: "#00a69d",
      textAlign: "center",
    },
    addButton: {
      backgroundColor: "#00a69d",
      padding: 16,
      borderRadius: 12,
      alignItems: "center",
      marginTop: 8,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    addButtonText: {
      color: "white",
      fontWeight: "700",
      fontSize: 16,
    },
    schedulesContainer: {
      backgroundColor: "#fff",
      borderRadius: 16,
      padding: 16,
      flex: 1 / 3,
      shadowColor: "#00a69d",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 3,
    },
    schedulesContent: {
      flex: 1,
      paddingBottom: 20,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: "700",
      marginBottom: 16,
      color: "#00a69d",
    },
    scheduleList: {
      paddingBottom: 20,
    },
    scheduleItem: {
      flexDirection: "row",
      justifyContent: "space-between",
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#7cced4",
      alignItems: "center",
    },
    scheduleInfo: {
      flex: 1,
      marginRight: 12,
    },
    medName: {
      fontWeight: "600",
      fontSize: 17,
      marginBottom: 6,
      color: "#00a69d",
    },
    doseText: {
      fontSize: 15,
      color: "#21aae1",
    },
    daysIndicator: {
      flexDirection: "row",
      minWidth: 160,
      justifyContent: "space-between",
    },
    dayIndicator: {
      fontSize: 15,
      color: "#60c4b4",
      fontWeight: "600",
    },
    activeDayIndicator: {
      color: "#00a69d",
    },
    deleteButton: {
      backgroundColor: "#fce8e6",
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      marginLeft: 10,
    },
    deleteButtonText: {
      color: "#d93025",
      fontSize: 18,
      fontWeight: "bold",
    },
    clearMedicationButton: {
      backgroundColor: "#fce8e6",
      padding: 12,
      borderRadius: 12,
      alignItems: "center",
      marginTop: 16,
    },
    selectedMedication: {
      backgroundColor: "#00a69d",
      padding: 12,
      borderRadius: 12,
      alignItems: "center",
      marginTop: 16,
      justifyContent: "center",
      flexDirection: "column",
      gap: 8,
    },
    clearMedicationChildren: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-evenly",
      gap: 8,
    },
    clearMedicationText: {
      color: "white",
      fontWeight: "600",
      fontSize: 16,
    },
    urgencyButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 4,
    },
    urgencyButton: {
      backgroundColor: "#ecebea",
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 12,
    },
    selectedUrgencyButton: {
      backgroundColor: "#00a69d",
    },
    urgencyButtonText: {
      color: "#00a69d",
      fontSize: 14,
    },
    selectedUrgencyText: {
      color: "white",
      fontWeight: "600",
      fontSize: 14,
    },
    emptyState: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 40,
    },
    emptyStateText: {
      fontSize: 18,
      color: "#60c4b4",
      fontWeight: "500",
      marginBottom: 8,
    },
    emptyStateSubtext: {
      fontSize: 14,
      color: "#21aae1",
      textAlign: "center",
    },
  }), [isPhone]); // Close the useMemo

  return {
    styles,
    isPhone,
    isWeb,
    width,
    height,
  };
};
