import { StyleSheet } from "react-native";

export const stylesPillboxSettings = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  content: {
    padding: 16,
    paddingBottom: 32,
  },
  imageContainer: {
    alignItems: "center",
    marginVertical: 20,
  },
  image: {
    width: 280,
    height: 200,
    borderRadius: 12,
    resizeMode: "contain",
  },
  formTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#222",
    textAlign: "center",
    marginVertical: 20,
  },
  compartmentContainer: {
    backgroundColor: "#ffffff",
    padding: 16,
    marginVertical: 8,
    borderRadius: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  compartmentTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#60c4b4",
    marginBottom: 12,
    textAlign: "center",
  },
  input: {
    marginBottom: 12,
    backgroundColor: "#fafafa",
  },
  saveButton: {
    marginTop: 24,
    paddingVertical: 8,
    borderRadius: 8,
  },
  patientCard: {
    backgroundColor: "#ffffff",
    marginVertical: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#222",
    marginBottom: 8,
    textAlign: "center",
  },
  sectionSubtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginBottom: 16,
  },
  patientList: {
    paddingVertical: 8,
  },
  patientItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  patientName: {
    fontSize: 16,
    color: "#222",
    marginLeft: 8,
    flex: 1,
  },
  noPatients: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    fontStyle: "italic",
    paddingVertical: 20,
  },
  quantityIndicator: {
    fontSize: 14,
    color: "#21aae1",
    fontWeight: "500",
  },
  scheduleSection: {
    marginTop: 16,
    padding: 12,
    backgroundColor: "#f9f9f9",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  scheduleSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#555",
    marginBottom: 12,
    textAlign: "center",
  },
  intervalLabel: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    paddingHorizontal: 8,
  },
  addTimeButton: {
    marginTop: 8,
    paddingVertical: 6,
    borderRadius: 6,
  },
  timeSlotContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginVertical: 4,
    backgroundColor: "#ffffff",
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  timeSlotText: {
    fontSize: 14,
    color: "#333",
    flex: 1,
  },
  removeTimeButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  removeTimeText: {
    color: "#ff6b6b",
    fontSize: 12,
    fontWeight: "600",
  },
  infoText: {
    color: "#f39c12",
    fontSize: 12,
    fontStyle: "italic",
    marginTop: 5,
    marginBottom: 10,
    textAlign: "center",
  },
});
